wrong patch...too many patches here also, update packages

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -60,6 +60,7 @@ known_hash_algos=('md5' 'sha1' 'sha224' 'sha256' 'sha384' 'sha512')
 
 # Options
 ASDEPS=0
+ASROOT=0
 BUILDFUNC=0
 CHECKFUNC=0
 CLEANBUILD=0
@@ -1048,7 +1049,7 @@ run_pacman() {
 	else
 		cmd=("$PACMAN_PATH" "$@")
 	fi
-	if [[ $1 != -@(T|Qq) ]]; then
+	if (( ! ASROOT )) && [[ ! $1 = -@(T|Qq) ]]; then
 		if type -p sudo >/dev/null; then
 			cmd=(sudo "${cmd[@]}")
 		else
@@ -2142,7 +2143,7 @@ write_pkginfo() {
 
 	msg2 "$(gettext "Generating %s file...")" ".PKGINFO"
 	printf "# Generated by makepkg %s\n" "$makepkg_version"
-	printf "# using %s\n" "$(fakeroot -v)"
+	(( INFAKEROOT )) && printf "# using %s\n" "$(fakeroot -v)"
 	printf "# %s\n" "$(LC_ALL=C date -u)"
 
 	printf "pkgname = %s\n" "$pkgname"
@@ -2949,7 +2950,7 @@ check_software() {
 	local ret=0
 
 	# check for PACMAN if we need it
-	if (( ! NODEPS || DEP_BIN || RMDEPS || INSTALL )); then
+	if (( ! INFAKEROOT && ( ! NODEPS || DEP_BIN || RMDEPS || INSTALL ) )); then
 		if [[ -z $PACMAN_PATH ]]; then
 			error "$(gettext "Cannot find the %s binary required for dependency operations.")" "$PACMAN"
 			ret=1
@@ -2957,16 +2958,17 @@ check_software() {
 	fi
 
 	# check for sudo if we will need it during makepkg execution
-	if (( DEP_BIN || RMDEPS || INSTALL )); then
+
+	if (( ! INFAKEROOT && ( DEP_BIN || RMDEPS || INSTALL ) )); then
 		if ! type -p sudo >/dev/null; then
 			warning "$(gettext "Cannot find the %s binary. Will use %s to acquire root privileges.")" "sudo" "su"
 		fi
 	fi
 
-	# fakeroot - correct package file permissions
+	# fakeroot - building as non-root user
 	if check_buildenv "fakeroot" "y" && (( EUID > 0 )); then
 		if ! type -p fakeroot >/dev/null; then
-			error "$(gettext "Cannot find the %s binary.")" "fakeroot"
+			error "$(gettext "Cannot find the %s binary required for building as non-root user.")" "fakeroot"
 			ret=1
 		fi
 	fi
@@ -3176,6 +3178,8 @@ usage() {
 	printf -- "$(gettext "  -S, --source     Generate a source-only tarball without downloaded sources")\n"
 	printf -- "$(gettext "  -V, --version    Show version information and exit")\n"
 	printf -- "$(gettext "  --allsource      Generate a source-only tarball including downloaded sources")\n"
+	printf -- "$(gettext "  --verifysource   Download source files (if needed) and perform integrity checks")\n"
+	printf -- "$(gettext "  --asroot         Allow %s to run as root user")\n" "makepkg"
 	printf -- "$(gettext "  --check          Run the %s function in the %s")\n" "check()" "$BUILDSCRIPT"
 	printf -- "$(gettext "  --config <file>  Use an alternate config file (instead of '%s')")\n" "$confdir/makepkg.conf"
 	printf -- "$(gettext "  --holdver        Do not update VCS sources")\n"
@@ -3227,7 +3231,7 @@ ARGLIST=("$@")
 
 # Parse Command Line Options.
 OPT_SHORT="AcCdefFghiLmop:rRsSV"
-OPT_LONG=('allsource' 'check' 'clean' 'cleanbuild' 'config:' 'force' 'geninteg'
+OPT_LONG=('allsource' 'asroot' 'check' 'clean' 'cleanbuild' 'config:' 'force' 'geninteg'
           'help' 'holdver' 'ignorearch' 'install' 'key:' 'log' 'noarchive' 'nobuild'
           'nocolor' 'nocheck' 'nodeps' 'noextract' 'noprepare' 'nosign' 'pkg:' 'repackage'
           'rmdeps' 'sign' 'skipchecksums' 'skipinteg' 'skippgpcheck' 'source' 'syncdeps'
@@ -3252,6 +3256,7 @@ while true; do
 
 		# Makepkg Options
 		--allsource)      SOURCEONLY=2 ;;
+		--asroot)         ASROOT=1 ;;
 		-A|--ignorearch)  IGNOREARCH=1 ;;
 		-c|--clean)       CLEANUP=1 ;;
 		-C|--cleanbuild)  CLEANBUILD=1 ;;
@@ -3439,9 +3444,21 @@ PACKAGER=${_PACKAGER:-$PACKAGER}
 CARCH=${_CARCH:-$CARCH}
 
 if (( ! INFAKEROOT )); then
-	if (( EUID == 0 )); then
-		error "$(gettext "Running %s as root is not allowed as it can cause permanent,\n\
-catastrophic damage to your system.")" "makepkg"
+	if (( EUID == 0 && ! ASROOT )); then
+		# Warn those who like to live dangerously.
+		error "$(gettext "Running %s as root is a BAD idea and can cause permanent,\n\
+catastrophic damage to your system. If you wish to run as root, please\n\
+use the %s option.")" "makepkg" "--asroot"
+		exit 1 # $E_USER_ABORT
+        elif (( EUID > 0 )) && ! check_buildenv "fakeroot" "y"; then
+                warning "$(gettext "Running %s as an unprivileged user will result in non-root\n\
+ownership of the packaged files. Try using the %s environment by\n\
+placing %s in the %s array in %s.")" "makepkg" "fakeroot" "'fakeroot'" "BUILDENV" "$MAKEPKG_CONF"
+                sleep 1
+	elif (( EUID > 0 && ASROOT )); then
+		# Warn those who try to use the --asroot option when they are not root
+		error "$(gettext "The %s option is meant for the root user only. Please\n\
+rerun %s without the %s flag.")" "--asroot" "makepkg" "--asroot"
 		exit 1 # $E_USER_ABORT
 	fi
 else
@@ -3608,7 +3625,12 @@ if (( SOURCEONLY )); then
 	check_source_integrity all
 	cd_safe "$startdir"
 
-	enter_fakeroot
+	# if we are root or if fakeroot is not enabled, then we don't use it
+        if ! check_buildenv "fakeroot" "y" || (( EUID == 0 )); then
+            create_srcpackage
+        else
+            enter_fakeroot
+        fi
 
 	msg "$(gettext "Source package created: %s")" "$pkgbase ($(date))"
 	exit 0
@@ -3690,13 +3712,38 @@ else
 	chmod a-srwx "$pkgdirbase"
 	cd_safe "$startdir"
 
-	if (( ! REPKG )); then
-		(( BUILDFUNC )) && run_build
-		(( CHECKFUNC )) && run_check
-		cd_safe "$startdir"
-	fi
+            # if we are root or if fakeroot is not enabled, then we don't use it
+            if ! check_buildenv "fakeroot" "y" || (( EUID == 0 )); then
+                    if (( ! REPKG )); then
+                            if (( ! ( SPLITPKG || PKGFUNC ) )); then
+                                    chmod 755 "$pkgdirbase"
+                                    mkdir -p "$pkgdir"
+                            fi
+                            (( BUILDFUNC )) && run_build
+                            (( CHECKFUNC )) && run_check
+                    fi
+                    chmod 755 "$pkgdirbase"
+                    if (( ! SPLITPKG )); then
+                            pkgdir="$pkgdirbase/$pkgname"
+                            mkdir -p "$pkgdir"
+                            if (( PKGFUNC )); then
+                                run_package
+                            fi
+                            tidy_install
+                            create_package
+                            create_debug_package
+                    else
+                            run_split_packaging
+                    fi
+            else
+                    if (( ! REPKG )); then
+                            (( BUILDFUNC )) && run_build
+                            (( CHECKFUNC )) && run_check
+                            cd_safe "$startdir"
+            fi
 
-	enter_fakeroot
+            enter_fakeroot
+	fi
 fi
 
 # if inhibiting archive creation, go no further
